const std = @import("std");
const array_list_compat = @import("array_list_compat");

const Allocator = std.mem.Allocator;

/// Provenance information for a piece of knowledge or output
pub const SourceProvenance = struct {
    allocator: Allocator,
    source_type: SourceType,
    origin: []const u8, // URL, file path, or model name
    retrieved_at: i64,
    confidence: f64, // 0.0-1.0
    parent_id: ?[]const u8, // ID of the source this was derived from

    pub const SourceType = enum {
        file, // Read from a local file
        web, // Retrieved from a URL
        ai_generated, // Generated by an AI model
        user_input, // Provided by the user
        tool_output, // Output from a tool execution
        wiki, // From internal knowledge base
        derived, // Computed/derived from other sources
    };

    pub fn init(allocator: Allocator, source_type: SourceType, origin: []const u8) !SourceProvenance {
        return SourceProvenance{
            .allocator = allocator,
            .source_type = source_type,
            .origin = try allocator.dupe(u8, origin),
            .retrieved_at = std.time.timestamp(),
            .confidence = 1.0,
            .parent_id = null,
        };
    }

    pub fn deinit(self: *SourceProvenance) void {
        self.allocator.free(self.origin);
        if (self.parent_id) |p| self.allocator.free(p);
    }

    pub fn withConfidence(self: *SourceProvenance, confidence: f64) *SourceProvenance {
        self.confidence = @max(0.0, @min(1.0, confidence));
        return self;
    }

    pub fn withParent(self: *SourceProvenance, parent_id: []const u8) !*SourceProvenance {
        self.parent_id = try self.allocator.dupe(u8, parent_id);
        return self;
    }
};

/// A tracked piece of knowledge with source attribution
pub const TrackedKnowledge = struct {
    allocator: Allocator,
    id: []const u8,
    content: []const u8,
    provenance: SourceProvenance,
    created_at: i64,
    tags: [][]const u8,

    pub fn init(
        allocator: Allocator,
        id: []const u8,
        content: []const u8,
        provenance: SourceProvenance,
    ) !TrackedKnowledge {
        return TrackedKnowledge{
            .allocator = allocator,
            .id = try allocator.dupe(u8, id),
            .content = try allocator.dupe(u8, content),
            .provenance = provenance,
            .created_at = std.time.timestamp(),
            .tags = &[_][]const u8{},
        };
    }

    pub fn deinit(self: *TrackedKnowledge) void {
        self.allocator.free(self.id);
        self.allocator.free(self.content);
        self.provenance.deinit();
        for (self.tags) |t| self.allocator.free(t);
        self.allocator.free(self.tags);
    }
};

/// Source-tracking metadata manager.
/// Tracks the origin and lineage of knowledge used in the session.
///
/// Usage:
///   var tracker = SourceTracker.init(allocator);
///   const prov = try SourceProvenance.init(allocator, .file, "src/main.zig");
///   try tracker.record("k1", "Main entry point", prov);
///   const report = tracker.provenanceReport();
///
/// Reference: LLM Wiki Guide source-tracking metadata (F19)
pub const SourceTracker = struct {
    allocator: Allocator,
    entries: array_list_compat.ArrayList(TrackedKnowledge),
    next_id: u32,

    pub fn init(allocator: Allocator) SourceTracker {
        return SourceTracker{
            .allocator = allocator,
            .entries = array_list_compat.ArrayList(TrackedKnowledge).init(allocator),
            .next_id = 1,
        };
    }

    pub fn deinit(self: *SourceTracker) void {
        for (self.entries.items) |*e| {
            e.deinit();
        }
        self.entries.deinit();
    }

    /// Record a piece of knowledge with source attribution
    pub fn record(self: *SourceTracker, id: []const u8, content: []const u8, provenance: SourceProvenance) !void {
        const entry = try TrackedKnowledge.init(self.allocator, id, content, provenance);
        try self.entries.append(entry);
        self.next_id += 1;
    }

    /// Record with auto-generated ID
    pub fn recordAuto(self: *SourceTracker, content: []const u8, provenance: SourceProvenance) ![]const u8 {
        const id = try std.fmt.allocPrint(self.allocator, "k{}", .{self.next_id});
        errdefer self.allocator.free(id);
        try self.record(id, content, provenance);
        return id;
    }

    /// Find entry by ID
    pub fn findById(self: *SourceTracker, id: []const u8) ?*TrackedKnowledge {
        for (self.entries.items) |*e| {
            if (std.mem.eql(u8, e.id, id)) return e;
        }
        return null;
    }

    /// Find all entries from a specific source type
    pub fn findBySourceType(self: *SourceTracker, source_type: SourceProvenance.SourceType) []const *TrackedKnowledge {
        var results = array_list_compat.ArrayList(*TrackedKnowledge).init(self.allocator);
        for (self.entries.items) |*e| {
            if (e.provenance.source_type == source_type) {
                results.append(e) catch {};
            }
        }
        return results.items;
    }

    /// Get entries count
    pub fn count(self: *const SourceTracker) u32 {
        return @intCast(self.entries.items.len);
    }

    /// Generate a provenance report showing source distribution
    pub fn provenanceReport(self: *const SourceTracker) ProvenanceReport {
        var file_count: u32 = 0;
        var web_count: u32 = 0;
        var ai_count: u32 = 0;
        var user_count: u32 = 0;
        var tool_count: u32 = 0;
        var wiki_count: u32 = 0;
        var derived_count: u32 = 0;
        var total_confidence: f64 = 0;

        for (self.entries.items) |e| {
            switch (e.provenance.source_type) {
                .file => file_count += 1,
                .web => web_count += 1,
                .ai_generated => ai_count += 1,
                .user_input => user_count += 1,
                .tool_output => tool_count += 1,
                .wiki => wiki_count += 1,
                .derived => derived_count += 1,
            }
            total_confidence += e.provenance.confidence;
        }

        const avg_confidence = if (self.entries.items.len > 0)
            total_confidence / @as(f64, @floatFromInt(self.entries.items.len))
        else
            0.0;

        return ProvenanceReport{
            .total_entries = @intCast(self.entries.items.len),
            .file_sources = file_count,
            .web_sources = web_count,
            .ai_sources = ai_count,
            .user_sources = user_count,
            .tool_sources = tool_count,
            .wiki_sources = wiki_count,
            .derived_sources = derived_count,
            .avg_confidence = avg_confidence,
        };
    }
};

pub const ProvenanceReport = struct {
    total_entries: u32,
    file_sources: u32,
    web_sources: u32,
    ai_sources: u32,
    user_sources: u32,
    tool_sources: u32,
    wiki_sources: u32,
    derived_sources: u32,
    avg_confidence: f64,
};

// ============================================================
// Tests
// ============================================================

const testing = std.testing;

test "SourceProvenance - init and deinit" {
    const p = try SourceProvenance.init(testing.allocator, .file, "src/main.zig");
    defer {
        var m = p;
        m.deinit();
    }
    try testing.expectEqual(SourceProvenance.SourceType.file, p.source_type);
    try testing.expectEqualStrings("src/main.zig", p.origin);
    try testing.expect(p.confidence == 1.0);
}

test "SourceProvenance - withConfidence clamps" {
    var p = try SourceProvenance.init(testing.allocator, .web, "https://example.com");
    defer p.deinit();
    _ = p.withConfidence(1.5);
    try testing.expect(p.confidence == 1.0);
    _ = p.withConfidence(-0.5);
    try testing.expect(p.confidence == 0.0);
}

test "SourceTracker - record and find" {
    var tracker = SourceTracker.init(testing.allocator);
    defer tracker.deinit();

    const p = try SourceProvenance.init(testing.allocator, .file, "test.zig");
    try tracker.record("k1", "Test knowledge", p);

    const found = tracker.findById("k1");
    try testing.expect(found != null);
    try testing.expectEqualStrings("Test knowledge", found.?.content);
}

test "SourceTracker - provenanceReport" {
    var tracker = SourceTracker.init(testing.allocator);
    defer tracker.deinit();

    const p1 = try SourceProvenance.init(testing.allocator, .file, "a.zig");
    try tracker.record("k1", "From file", p1);

    const p2 = try SourceProvenance.init(testing.allocator, .ai_generated, "llama3");
    try tracker.record("k2", "From AI", p2);

    const report = tracker.provenanceReport();
    try testing.expectEqual(@as(u32, 2), report.total_entries);
    try testing.expectEqual(@as(u32, 1), report.file_sources);
    try testing.expectEqual(@as(u32, 1), report.ai_sources);
}
